package processor

type Instruction struct {
	Name           string                          // Instruction name
	AddressingMode func() Operand                  // Addressing Mode
	Length         byte                            // Length in bytes
	Cycles         byte                            // Base cycles !!!(Additional cycles are not taken into account and are added during the execution of the opcode)
	Execute        func(cpu *CPU, operand Operand) // Opcode handler
}

var OpcodeTable = map[byte]Instruction{
	0x69: {
		Name:           "ADC",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Adc,
	},
	0x65: {
		Name:           "ADC",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Adc,
	},
	0x75: {
		Name:           "ADC",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Adc,
	},
	0x6D: {
		Name:           "ADC",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Adc,
	},
	0x7D: {
		Name:           "ADC",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Adc,
	},
	0x79: {
		Name:           "ADC",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Adc,
	},
	0x61: {
		Name:           "ADC",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Adc,
	},
	0x71: {
		Name:           "ADC",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Adc,
	},
	0x18: {
		Name:           "CLC",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Clc,
	},
	0x38: {
		Name:           "SEC",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Sec,
	},
	0x58: {
		Name:           "CLI",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Cli,
	},
	0x78: {
		Name:           "SEI",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Sei,
	},
	0xB8: {
		Name:           "CLV",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Clv,
	},
	0xD8: {
		Name:           "CLD",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Cld,
	},
	0xF8: {
		Name:           "SED",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Sed,
	},
	0x24: {
		Name:           "BIT",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Bit,
	},
	0x2C: {
		Name:           "BIT",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Bit,
	},
	0x10: {
		Name:           "BPL",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bpl,
	},
	0x30: {
		Name:           "BMI",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bmi,
	},
	0x50: {
		Name:           "BVC",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bvc,
	},
	0x70: {
		Name:           "BVS",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bvs,
	},
	0x90: {
		Name:           "BCC",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bcc,
	},
	0xB0: {
		Name:           "BCS",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bcs,
	},
	0xD0: {
		Name:           "BNE",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Bne,
	},
	0xF0: {
		Name:           "BEQ",
		AddressingMode: Relative,
		Length:         2,
		Cycles:         2,
		Execute:        Beq,
	},
	0x00: {
		Name:           "BRK",
		AddressingMode: Implied,
		Length:         2,
		Cycles:         7,
		Execute:        Brk,
	},
	0x0A: {
		Name:           "ASL",
		AddressingMode: Accumulator,
		Length:         1,
		Cycles:         2,
		Execute:        Asl,
	},
	0x06: {
		Name:           "ASL",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Asl,
	},
	0x16: {
		Name:           "ASL",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Asl,
	},
	0x0E: {
		Name:           "ASL",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Asl,
	},
	0x1E: {
		Name:           "ASL",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Asl,
	},
	0xEA: {
		Name:           "NOP",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Nop,
	},
	0x48: {
		Name:           "PHA",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         3,
		Execute:        Pha,
	},
	0x08: {
		Name:           "PHP",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         3,
		Execute:        Php,
	},
	0x28: {
		Name:           "PLP",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         4,
		Execute:        Plp,
	},
	0x68: {
		Name:           "PLA",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         4,
		Execute:        Pla,
	},
	0xAA: {
		Name:           "TAX",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Tax,
	},
	0xA8: {
		Name:           "TAY",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Tay,
	},
	0xBA: {
		Name:           "TSX",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Tsx,
	},
	0x8A: {
		Name:           "TXA",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Txa,
	},
	0x9A: {
		Name:           "TXS",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Txs,
	},
	0x98: {
		Name:           "TYA",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Tya,
	},
	0x40: {
		Name:           "RTI",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         6,
		Execute:        Rti,
	},
	0x60: {
		Name:           "RTS",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         6,
		Execute:        Rts,
	},
	0x4C: {
		Name:           "JMP",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         3,
		Execute:        Jmp,
	},
	0x6C: {
		Name:           "JMP",
		AddressingMode: AbsoluteIndirect,
		Length:         3,
		Cycles:         5,
		Execute:        Jmp,
	},
	0x20: {
		Name:           "JSR",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Jsr,
	},
	0x4A: {
		Name:           "LSR",
		AddressingMode: Accumulator,
		Length:         1,
		Cycles:         2,
		Execute:        Lsr,
	},
	0x4E: {
		Name:           "LSR",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Lsr,
	},
	0x5E: {
		Name:           "LSR",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Lsr,
	},
	0x46: {
		Name:           "LSR",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Lsr,
	},
	0x56: {
		Name:           "LSR",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Lsr,
	},
	0x2A: {
		Name:           "ROL",
		AddressingMode: Accumulator,
		Length:         1,
		Cycles:         2,
		Execute:        Rol,
	},
	0x2E: {
		Name:           "ROL",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Rol,
	},
	0x3E: {
		Name:           "ROL",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Rol,
	},
	0x26: {
		Name:           "ROL",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Rol,
	},
	0x36: {
		Name:           "ROL",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Rol,
	},
	0x6A: {
		Name:           "ROR",
		AddressingMode: Accumulator,
		Length:         1,
		Cycles:         2,
		Execute:        Ror,
	},
	0x6E: {
		Name:           "ROR",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Ror,
	},
	0x7E: {
		Name:           "ROR",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Ror,
	},
	0x66: {
		Name:           "ROR",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Ror,
	},
	0x76: {
		Name:           "ROR",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Ror,
	},
	0xE8: {
		Name:           "INX",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Inx,
	},
	0xC8: {
		Name:           "INY",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Iny,
	},
	0xCA: {
		Name:           "DEX",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Dex,
	},
	0x88: {
		Name:           "DEY",
		AddressingMode: Implied,
		Length:         1,
		Cycles:         2,
		Execute:        Dey,
	},
	0x29: {
		Name:           "AND",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        And,
	},
	0x2D: {
		Name:           "AND",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        And,
	},
	0x3D: {
		Name:           "AND",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        And,
	},
	0x39: {
		Name:           "AND",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        And,
	},
	0x25: {
		Name:           "AND",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        And,
	},
	0x35: {
		Name:           "AND",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        And,
	},
	0x21: {
		Name:           "AND",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        And,
	},
	0x31: {
		Name:           "AND",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        And,
	},
	0x09: {
		Name:           "ORA",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Ora,
	},
	0x0D: {
		Name:           "ORA",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ora,
	},
	0x1D: {
		Name:           "ORA",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ora,
	},
	0x19: {
		Name:           "ORA",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ora,
	},
	0x05: {
		Name:           "ORA",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Ora,
	},
	0x15: {
		Name:           "ORA",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Ora,
	},
	0x01: {
		Name:           "ORA",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Ora,
	},
	0x11: {
		Name:           "ORA",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Ora,
	},
	0x49: {
		Name:           "EOR",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Eor,
	},
	0x4D: {
		Name:           "EOR",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Eor,
	},
	0x5D: {
		Name:           "EOR",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Eor,
	},
	0x59: {
		Name:           "EOR",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Eor,
	},
	0x45: {
		Name:           "EOR",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Eor,
	},
	0x55: {
		Name:           "EOR",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Eor,
	},
	0x41: {
		Name:           "EOR",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Eor,
	},
	0x51: {
		Name:           "EOR",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Eor,
	},
	0xEE: {
		Name:           "INC",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Inc,
	},
	0xFE: {
		Name:           "INC",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Inc,
	},
	0xE6: {
		Name:           "INC",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Inc,
	},
	0xF6: {
		Name:           "INC",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Inc,
	},
	0xCE: {
		Name:           "DEC",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         6,
		Execute:        Dec,
	},
	0xDE: {
		Name:           "DEC",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         7,
		Execute:        Dec,
	},
	0xC6: {
		Name:           "DEC",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         5,
		Execute:        Dec,
	},
	0xD6: {
		Name:           "DEC",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         6,
		Execute:        Dec,
	},
	0xC9: {
		Name:           "CMP",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Cmp,
	},
	0xCD: {
		Name:           "CMP",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Cmp,
	},
	0xDD: {
		Name:           "CMP",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Cmp,
	},
	0xD9: {
		Name:           "CMP",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Cmp,
	},
	0xC5: {
		Name:           "CMP",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Cmp,
	},
	0xD5: {
		Name:           "CMP",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Cmp,
	},
	0xC1: {
		Name:           "CMP",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Cmp,
	},
	0xD1: {
		Name:           "CMP",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Cmp,
	},
	0xE0: {
		Name:           "CPX",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Cpx,
	},
	0xEC: {
		Name:           "CPX",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Cpx,
	},
	0xE4: {
		Name:           "CPX",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Cpx,
	},
	0xC0: {
		Name:           "CPY",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Cpy,
	},
	0xCC: {
		Name:           "CPY",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Cpy,
	},
	0xC4: {
		Name:           "CPY",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Cpy,
	},
	0xE9: {
		Name:           "SBC",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Sbc,
	},
	0xED: {
		Name:           "SBC",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Sbc,
	},
	0xFD: {
		Name:           "SBC",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Sbc,
	},
	0xF9: {
		Name:           "SBC",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Sbc,
	},
	0xE5: {
		Name:           "SBC",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Sbc,
	},
	0xF5: {
		Name:           "SBC",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Sbc,
	},
	0xE1: {
		Name:           "SBC",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Sbc,
	},
	0xF1: {
		Name:           "SBC",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Sbc,
	},
	0xA2: {
		Name:           "LDX",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Ldx,
	},
	0xAE: {
		Name:           "LDX",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ldx,
	},
	0xBE: {
		Name:           "LDX",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ldx,
	},
	0xA6: {
		Name:           "LDX",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Ldx,
	},
	0xB6: {
		Name:           "LDX",
		AddressingMode: YIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Ldx,
	},
	0xA0: {
		Name:           "LDY",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Ldy,
	},
	0xAC: {
		Name:           "LDY",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ldy,
	},
	0xBC: {
		Name:           "LDY",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Ldy,
	},
	0xA4: {
		Name:           "LDY",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Ldy,
	},
	0xB4: {
		Name:           "LDY",
		AddressingMode: YIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Ldy,
	},
	0x8E: {
		Name:           "STX",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Stx,
	},
	0x86: {
		Name:           "STX",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Stx,
	},
	0x96: {
		Name:           "STX",
		AddressingMode: YIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Stx,
	},
	0x8C: {
		Name:           "STY",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Sty,
	},
	0x84: {
		Name:           "STY",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Sty,
	},
	0x94: {
		Name:           "STY",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Sty,
	},
	0x8D: {
		Name:           "STA",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Sta,
	},
	0x9D: {
		Name:           "STA",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         5,
		Execute:        Sta,
	},
	0x99: {
		Name:           "STA",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         5,
		Execute:        Sta,
	},
	0x85: {
		Name:           "STA",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Sta,
	},
	0x95: {
		Name:           "STA",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Sta,
	},
	0x81: {
		Name:           "STA",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Sta,
	},
	0x91: {
		Name:           "STA",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Sta,
	},
	0xA9: {
		Name:           "LDA",
		AddressingMode: Immediate,
		Length:         2,
		Cycles:         2,
		Execute:        Lda,
	},
	0xAD: {
		Name:           "LDA",
		AddressingMode: Absolute,
		Length:         3,
		Cycles:         4,
		Execute:        Lda,
	},
	0xBD: {
		Name:           "LDA",
		AddressingMode: XIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Lda,
	},
	0xB9: {
		Name:           "LDA",
		AddressingMode: YIndexedAbsolute,
		Length:         3,
		Cycles:         4,
		Execute:        Lda,
	},
	0xA5: {
		Name:           "LDA",
		AddressingMode: ZeroPage,
		Length:         2,
		Cycles:         3,
		Execute:        Lda,
	},
	0xB5: {
		Name:           "LDA",
		AddressingMode: XIndexedZeroPage,
		Length:         2,
		Cycles:         4,
		Execute:        Lda,
	},
	0xA1: {
		Name:           "LDA",
		AddressingMode: XIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         6,
		Execute:        Lda,
	},
	0xB1: {
		Name:           "LDA",
		AddressingMode: YIndexedZeroPageIndirect,
		Length:         2,
		Cycles:         5,
		Execute:        Lda,
	},
}
