package processor

type Instruction struct {
	Name            string                      // Instruction name
	Addressing_mode func(address uint16) *byte  // Addressing Mode
	Length          byte                        // Length in bytes
	Cycles          byte                        // Base cycles !!!(Additional cycles are not taken into account and are added during the execution of the opcode)
	Execute         func(cpu *CPU, value *byte) // Opcode handler
}

var OpcodeTable = map[byte]Instruction{
	0x69: {
		Name:            "ADC_IMM",
		Addressing_mode: Immediate,
		Length:          2,
		Cycles:          2,
		Execute:         Adc,
	},
	0x65: {
		Name:            "ADC_ZP",
		Addressing_mode: ZeroPage,
		Length:          2,
		Cycles:          3,
		Execute:         Adc,
	},
	0x75: {
		Name:            "ADC_ZPX",
		Addressing_mode: XIndexedZeroPage,
		Length:          2,
		Cycles:          4,
		Execute:         Adc,
	},
	0x6D: {
		Name:            "ADC_ABS",
		Addressing_mode: Absolute,
		Length:          3,
		Cycles:          4,
		Execute:         Adc,
	},
	0x7D: {
		Name:            "ADC_ABSX",
		Addressing_mode: XIndexedAbsolute,
		Length:          3,
		Cycles:          4,
		Execute:         Adc,
	},
	0x79: {
		Name:            "ADC_ABSY",
		Addressing_mode: YIndexedAbsolute,
		Length:          3,
		Cycles:          4,
		Execute:         Adc,
	},
	0x61: {
		Name:            "ADC_ZPIX",
		Addressing_mode: XIndexedZeroPageInderect,
		Length:          2,
		Cycles:          6,
		Execute:         Adc,
	},
	0x71: {
		Name:            "ADC_ZPIY",
		Addressing_mode: YIndexedZeroPageInderect,
		Length:          2,
		Cycles:          5,
		Execute:         Adc,
	},
	0x18: {
		Name:            "CLC",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Clc,
	},
	0x38: {
		Name:            "SEC",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Sec,
	},
	0x58: {
		Name:            "CLI",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Cli,
	},
	0x78: {
		Name:            "SEI",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Sei,
	},
	0xB8: {
		Name:            "CLV",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Clv,
	},
	0xD8: {
		Name:            "CLD",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Cld,
	},
	0xF8: {
		Name:            "SED",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Sed,
	},
	0x24: {
		Name:            "BIT_ZP",
		Addressing_mode: ZeroPage,
		Length:          2,
		Cycles:          3,
		Execute:         Bit,
	},
	0x2C: {
		Name:            "BIT_ABS",
		Addressing_mode: Absolute,
		Length:          3,
		Cycles:          4,
		Execute:         Bit,
	},
	0x10: {
		Name:            "BPL",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bpl,
	},
	0x30: {
		Name:            "BMI",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bmi,
	},
	0x50: {
		Name:            "BVC",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bvc,
	},
	0x70: {
		Name:            "BVS",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bvs,
	},
	0x90: {
		Name:            "BCC",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bcc,
	},
	0xB0: {
		Name:            "BCS",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bcs,
	},
	0xD0: {
		Name:            "BNE",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Bne,
	},
	0xF0: {
		Name:            "BEQ",
		Addressing_mode: Relative,
		Length:          2,
		Cycles:          2,
		Execute:         Beq,
	},
	0x00: {
		Name:            "BRK",
		Addressing_mode: Implied,
		Length:          2,
		Cycles:          7,
		Execute:         Brk,
	},
	0x0A: {
		Name:            "ASL_ACC",
		Addressing_mode: Accumulator,
		Length:          1,
		Cycles:          2,
		Execute:         Asl,
	},
	0x06: {
		Name:            "ASL_ZP",
		Addressing_mode: ZeroPage,
		Length:          2,
		Cycles:          5,
		Execute:         Asl,
	},
	0x16: {
		Name:            "ASL_ZPX",
		Addressing_mode: XIndexedZeroPage,
		Length:          2,
		Cycles:          6,
		Execute:         Asl,
	},
	0x0E: {
		Name:            "ASL_ABS",
		Addressing_mode: Absolute,
		Length:          3,
		Cycles:          6,
		Execute:         Asl,
	},
	0x1E: {
		Name:            "ASL_ABSX",
		Addressing_mode: XIndexedAbsolute,
		Length:          3,
		Cycles:          7,
		Execute:         Asl,
	},
	0xEA: {
		Name:            "NOP",
		Addressing_mode: Implied,
		Length:          1,
		Cycles:          2,
		Execute:         Nop,
	},
}
